### ISSUE TITLE
Remove image after loading into container image

### ISSUE THREAD

**Issue by hangy** [ishworkh/container-image-artifact-download#7]
We noticed that the image file is intentionally kept in `/tmp` after it's loaded into the container engine. With our (arguably too) large image, this can lead to the GitHub Actions runner running out of space.

I'd like to propose an additional input:
```yaml
  retain_image_file:
    description: Retain image file after loading the image into container engine.
    required: false
    default: "true"
```

If the `true` is passed, then the current behaviour of the action would performed; otherwise the file would be deleted after loading it into podman/docker. If the file's deleted, then `download_path` would not be set to the path of the temporary image file.

We tested that this indeed helps for our workflow by manually removing the image file with a script task. However, I think this could be useful as a standard parameter, because people may just not need the .tar.gz after the image has been copied to docker/podman.

I can suggest a PR if this sounds like something you'd be open to integrate. 😄
